apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pulse
  namespace: pulse
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: pulse.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: pulse-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pulse-ui
                port:
                  number: 80
